Discord auth
Osmose/ribbit-recipes pull request #2
Opened 2024-04-07 00:52 UTC by Osmose

🙏

2024-04-07 06:30 UTC, ElusiveEllie requested changes
Small spelling error

2024-04-07 06:30 UTC, ElusiveEllie commented on index.html
> +    <title>ribbet-recipes</title>
Misspelled "Ribbit" again

2024-04-07 06:30 UTC, ElusiveEllie commented on src/components/App.tsx
> +        <Route component={Landing} />
I think eventually we'll want the default to be a 404 page, and just have `"/"` be the landing, right?

2024-04-08 18:37 UTC, Osmose commented
Updated with fixes

2024-04-10 03:58 UTC, ElusiveEllie approved these changes

2024-04-11 03:52 UTC, merged